#!/usr/bin/with-contenv bash

echo
echo "-------------------------------------"
echo "Starting TráfegoDNS..."
echo "-------------------------------------"
echo
cd /app
exec s6-setuidgid abc node src/app-enhanced.js